{{if .Values.eureka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metersphere-eureka
spec:
  replicas: {{.Values.eureka.replicas | default 1}}
  selector:
    matchLabels:
      app: metersphere-eureka
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metersphere-eureka
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - metersphere-eureka
              topologyKey: kubernetes.io/hostname
      containers:
        - name: metersphere-eureka
          image: {{.Values.common.imagePrefix}}{{.Values.eureka.image}}:{{.Values.common.imageTag}}
          imagePullPolicy: {{.Values.common.imagePullPolicy}}
          resources:
            limits:
              memory: 800Mi
            requests:
              memory: 300Mi
              cpu: 0.1
          ports:
            - name: http
              containerPort: 8761
          env: 
            - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
              value: "true"
          volumeMounts:
            - mountPath: /opt/metersphere/conf
              name: opt-metersphere-config
            - mountPath: /opt/metersphere/logs
              name: metersphere-logs
            - mountPath: /opt/metersphere/data
              name: metersphere-data
      {{if ne (.Values.common.imagePullSecrets | default "nil") "nil"}}
      imagePullSecrets:
        - name: {{.Values.common.imagePullSecrets}}
      {{ end }}
      volumes:
        - configMap:
            defaultMode: 420
            name: metersphere-config
            items:
            - key: metersphere.properties
              path: metersphere.properties
            - key: redisson.yml
              path: redisson.yml
          name: opt-metersphere-config
        - name: metersphere-logs
          {{if .Values.logPersistence.enabled}}
          persistentVolumeClaim:
            claimName: metersphere-logs-pvc
          {{ else }}
          emptyDir: {}
          {{ end }}
        - name: metersphere-data
          {{if .Values.dataPersistence.enabled}}
          persistentVolumeClaim:
            claimName: metersphere-data-pvc
          {{ else }}
          emptyDir: {}
          {{ end }}
        - name: scripts
          configMap:
            name: metersphere-scripts
            defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: metersphere-eureka
  labels:
    app: metersphere-eureka
spec:
  sessionAffinity: ClientIP
  selector:
    app: metersphere-eureka
  ports:
    - name: http
      port: 8761
      protocol: TCP
{{end}}