apiVersion: v1
kind: ConfigMap
metadata:
  name: metersphere-config
data:
  metersphere.properties: |-
    {{ tpl .Values.common.properties . | nindent 4 }}
  redisson.yml: |-
    {{ tpl .Values.redisson.yml . | nindent 4 }}
  kafka.bootstrap-servers: ""
