apiVersion: v2
appVersion: 2.10.21-lts
description: A Helm chart to deploy MeterSphere
engine: gotpl
home: https://metersphere.io
icon: https://metersphere.io/images/logo/favicon.ico
maintainers:
- email: metersphere@fit2cloud.com
  name: metersphere
name: metersphere
sources:
- https://github.com/metersphere/
dependencies:
- name: kafka
  repository: https://charts.bitnami.com/bitnami
  condition: kafka.enabled
  version: 26.0.0
version: 2.10.21
