{{if .Values.ingress.enabled}}
apiVersion: {{ include "metersphere.ingress.apiVersion" . }}
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  name: metersphere
spec:
  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metersphere-gateway
                port:
                  number: 8000
{{if .Values.ingress.https.enabled}}
  tls:
    - hosts:
        - {{.Values.ingress.host}}
      secretName: {{.Values.ingress.https.secretName}}
{{ end }}
{{ end }}
