{{if and .Values.kafka.enabled .Values.kafka.externalAccess.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metersphere
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch      
      - update      
      - patch      
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metersphere
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metersphere
roleRef:
  kind: Role
  name: metersphere
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: metersphere
    namespace: {{ .Release.Namespace }}
{{ end }}

